-- 코드를 입력하세요
SELECT CAR_INFO.CAR_ID, CAR_INFO.CAR_TYPE, ROUND(CAR_INFO.DAILY_FEE * ((100 - DISCOUNT.DISCOUNT_RATE) / 100) * 30, 0) AS FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C 
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE IN ('세단', 'SUV')
    GROUP BY H.CAR_ID
    HAVING MAX(H.START_DATE) >= '2022-12-01' OR MAX(H.END_DATE) <= '2022-11-01 00:00:00') AS CAR_INFO
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT ON CAR_INFO.CAR_TYPE = DISCOUNT.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상' AND ROUND(CAR_INFO.DAILY_FEE * ((100 - DISCOUNT.DISCOUNT_RATE) / 100) * 30, 0) >= 500000 AND ROUND(CAR_INFO.DAILY_FEE * ((100 - DISCOUNT.DISCOUNT_RATE) / 100) * 30, 0) <= 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID;