-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS A
WHERE (FAVORITES, FOOD_TYPE) IN (
    SELECT MAX(FAVORITES), FOOD_TYPE
    FROM REST_INFO AS B
    GROUP BY B.FOOD_TYPE
)
GROUP BY A.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC;