-- 코드를 작성해주세요
WITH TOTAL_COUNT AS (
    SELECT COUNT(*) AS CNT FROM ECOLI_DATA
)

SELECT ID, 
    CASE
        WHEN NUM <= (CNT / 4) THEN 'CRITICAL'
        WHEN NUM <= 2 * (CNT / 4) THEN 'HIGH'
        WHEN NUM <= 3 * (CNT / 4) THEN 'MEDIUM'
        ELSE 'LOW'
    END 'COLONY_NAME'
FROM (SELECT ID, SIZE_OF_COLONY, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS NUM
FROM ECOLI_DATA) AS D, TOTAL_COUNT
ORDER BY ID;
