-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", FILE.BOARD_ID, "/", FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS BOARD, USED_GOODS_FILE AS FILE
WHERE BOARD.BOARD_ID = FILE.BOARD_ID AND BOARD.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC;